apiVersion: v1
kind: Service
metadata:
  name: android-emulator
  namespace: android-emulation
spec:
  type: NodePort
  selector:
    app: android-emulator
  ports:
  - name: adb
    port: 5555
    targetPort: 5556
    nodePort: 30555
    protocol: TCP
