apiVersion: v1
kind: Service
metadata:
  name: cuttlefish-webrtc
  namespace: android-emulation
spec:
  type: NodePort
  selector:
    app: cuttlefish
  ports:
  - name: webrtc
    port: 8443
    targetPort: 8443
    nodePort: 30443
    protocol: TCP
  - name: adb
    port: 6520
    targetPort: 6520
    nodePort: 30550
    protocol: TCP